### ISSUE TITLE
error in JSONP old messages response

### ISSUE THREAD

**Issue by megabuz** [wandenberg/nginx-push-stream-module#123]
sometimes i get array of messages without comma separators
```
[{"id":...}{"id":...}]
```
sometimes ngx_http_output_filter returns NGX_AGAIN (maybe when i have big message). So in ngx_http_push_stream_module_utils.c (line 516)
```
            if (rc == NGX_OK) {
                rc = ngx_http_push_stream_send_response_text(r, str->data, str->len, 0);
            }

            if ((rc == NGX_OK) && use_jsonp) {
```
rc can be NGX_AGAIN

i found answer in http://mailman.nginx.org/pipermail/nginx/2007-September/001791.html

> If you have got all your data ready you may send them at once in one chain.
> But if you are getting then gradually, then after NGX_AGAIN you should
> set event handlers and timer and return control to nginx.

Can you fix this error? 
Thanks

**Comment by wandenberg** [comment]
The problem with NGX_AGAIN was solved on 0.5.1 tag (a48ca949427b782fba1722932f4881850c50b9f1)
