### ISSUE TITLE
issue running under windows

### ISSUE THREAD

**Issue by nikolaydimitrov** [wandenberg/nginx-push-stream-module#132]
Hi,

The module compiles fine on both Linux and Windows but using the same version of nginx - 1.4.6 from source and version 3d3a204 of this module, the Linux version runs fine and the Windows throws this error:

nginx: [crit] ngx_slab_alloc() failed: no memory

I'm using the sample configuration for WebSockets and no matter what values I use for push_stream_shared_memory_size, it always throws that on Windows.

Cheers

Edit: Forgot to mention that this has been compiled using cygwin:
Target: i686-pc-cygwin
gcc version 4.8.2 (GCC)

**Comment by wandenberg** [comment]
Are you still having this problem?
Are you still trying to run the module on cygwin?

**Comment by nikolaydimitrov** [comment]
Not really, we are just compiling it for Linux now.
Thanks for asking!

**Comment by wandenberg** [comment]
OK. Tell me if you have any other problem.
