### ISSUE TITLE
Memory leak - getting HTTP 500

### ISSUE THREAD

**Issue by ghost** [wandenberg/nginx-push-stream-module#138]
Hi,

We use the push stream module in the WS configuration to send messages to clients. It appears that the Nginx process size keeps increasing indefinitely and after a while we start getting HTTP 500 from the server. The log says: **ngx_slab_alloc() failed: no memory**. Some of our messages are 15-20KB in size.

I understand that this is actually an Nginx issue, not a push stream issue per se.
I've found this discussion: https://github.com/wandenberg/nginx-push-stream-module/issues/87
and the patch you posted there: https://gist.github.com/wandenberg/6096183

Has this patch been pulled into the main Nginx trunk? Because it doesn't seem like the issue has been resolved.

Could you please point us in the right direction as to how to handle this situation? Right now it seems that the only way to resolve this is to regularly restart Nginx. Is there another way to handle this?

Many thanks

**Comment by qianxinyu** [comment]
I ran into this problem too and I already use the 1.8 the latest Nginx in which version I think the bug has been fixed. Have I missed something? Are there any config items to set the memory usage of Nginx ?
