### ISSUE TITLE
restore channels and messages after restart of nginx

### ISSUE THREAD

**Issue by funkydonkey123** [wandenberg/nginx-push-stream-module#159]
For some reasons people might have to restart nginx. Currently I see no way to restore the saved messages and channels from before nginx restarted. Maybe this one would be very important for others as well?

**Comment by msurguy** [comment]
The messages should be stored on the server that will then ping nginx-push-stream-module to publish them so that responsibility should not be a part of this module at all.

@wandenberg  I think this can be closed, right?
