### ISSUE TITLE
Can not get old message when init connection

### ISSUE THREAD

**Issue by KimShen** [wandenberg/nginx-push-stream-module#160]
Can not get old message when init connection,
Version: 0.4.0

Following the 'long_polling.textile' to config the 'Getting old messages' function:
location /pub {
        push_stream_publisher admin;
        push_stream_store_messages on;
        push_stream_channels_path    $arg_id;
}
location ~ /lp/(.*) {
        push_stream_subscriber long-polling;
        push_stream_last_received_message_time "$arg_time";
        push_stream_last_received_message_tag   "$arg_tag";
        push_stream_channels_path $1;
        push_stream_message_template                "{\"id\":~id~,\"channel\":\"~channel~\",\"text\":\"~text~\",\"tag\":\"~tag~\",\"time\":\"~time~\"}";
        push_stream_longpolling_connection_ttl 30s;
}

Html:
<html>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
</head>
<body>
    <p>Messages:</p>
    <div id="messages" style="width:800px;height:300px;overflow:scroll;"></div>
    <script src="/js/pushstream.js" type="text/javascript" language="javascript" charset="utf-8"></script>
    <script type="text/javascript" language="javascript" charset="utf-8">
    // <![CDATA[
    function messageReceived(text, id, channel) {
      document.getElementById('messages').innerHTML += id + ': ' + text + '<br>';
    };
    var pushstream = new PushStream({
      host: window.location.hostname,
      port: window.location.port,
      modes: "longpolling",
      messagesPublishedAfter: 50,
      messagesControlByArgument: true
    });
    pushstream.onmessage = messageReceived;
    pushstream.addChannel('ch1');
    pushstream.connect();
    // ]]>
    </script>
</body>
</html>

Best Regards,

**Comment by mobinvestor** [comment]
I have the same problem ((
How you fixed it?
