### ISSUE TITLE
All Channels Stats detailed and channel_inactivity_time

### ISSUE THREAD

**Issue by marul2** [wandenberg/nginx-push-stream-module#164]
It would be very useful to have in the "All Channels Stats detailed" view, the time-stamp when the last subscriber entered.

Also for channel_inactivity_time take into account only when the last subscriber entered. Why? Because I send messages to the channel while has subscribers, so the channel never dies although there is nobody listening.

**Comment by wandenberg** [comment]
Hi @marul2 
on channels stats you have the number of subscribers connected on the channel.
Isn't this enough to know when you have to stop to send messages to the channel?
