### ISSUE TITLE
Send message to channel by name

### ISSUE THREAD

**Issue by jpascal** [wandenberg/nginx-push-stream-module#173]
How I can send message to channel by name using pushstream.js?

**Comment by wandenberg** [comment]
If you want to send the message to all channels which you are connected in, just call the sendMessage on your pushshtream instance like

```javascript
var pushstream = new PushStream({...});
pushstream.sendMessage(message, successCallback, errorCallback);
```

If you want to puslish a message to a specific channel you could do like this

```javascript
PushStream.sendMessage(url, message, successCallback, errorCallback);
```

**Comment by jpascal** [comment]
Thanks
