### ISSUE TITLE
This module performance data.

### ISSUE THREAD

**Issue by agile6v** [wandenberg/nginx-push-stream-module#175]
Hi, @wandenberg 

Is there any pressure-tested?

How much is the concurrency of this module?

**Comment by wandenberg** [comment]
Hi @agile6v 

The concurrency depends on your hardware and your application.
I received reports of some apps with 500k subscribers or more.
Take a look on this http://highscalability.com/blog/2014/4/28/how-disqus-went-realtime-with-165k-messages-per-second-and-l.html

**Comment by agile6v** [comment]
Thank you. @wandenberg
