### ISSUE TITLE
cant read in java BufferedReader BLOCKING read

### ISSUE THREAD

**Issue by NicoCaballero** [wandenberg/nginx-push-stream-module#179]
Hi, im have a problem. the messages coming but never finish the while!
The read block and never leave of while..
Any know why ??

im have this code in java:

                Writer writer = new StringWriter();
                char[] buffer = new char[1024];	            
                BufferedReader  reader = new BufferedReader(new InputStreamReader(ins, "UTF-8"));
                int n;

                while((n = reader.read(buffer)) != -1){
                	writer.write(buffer, 0, n);
                        System.out.println(writer.toString());
                }

my config in ngix

   #Push module

        location /channels-stats {

                # activate channels statistics mode for this location

                push_stream_channels_statistics;

                # query string based channel id

                push_stream_channels_path               $arg_id;

        }

        location /pub {

                # activate publisher (admin) mode for this location

                push_stream_publisher admin;

                # query string based channel id

                push_stream_channels_path    $arg_id;

                push_stream_store_messages on;

        }

        location ~ /sub/(.*) {

                # activate subscriber (streaming) mode for this location

                push_stream_subscriber;

                # positional channel path

                push_stream_channels_path                     $1;

                # message template

                push_stream_message_template                "{\"id\":~id~,\"channel\":\"~channel~\",\"text\":\"~text~\",\"tag\":\"~tag~\",\"time\":\"~time~\"}";

        }

**Comment by wandenberg** [comment]
You are in a stream connection. So the client will wait until a new byte is
received.

You may set a timeout on read operation or use the long polling mode, your
connection will be closed at the server as soon as it sends the message to
the client, and the client have to reconnect sending the proper values of
the last received message. Take a look on the curl examples at the readme.

**Comment by NicoCaballero** [comment]
Thanks.
