### ISSUE TITLE
Specific ip only open all channel

### ISSUE THREAD

**Issue by NicoCaballero** [wandenberg/nginx-push-stream-module#181]
You can specify an IP to only this can open the channels?
Only to open them. then reading and writing without filter.

Thanks.

**Comment by tomquas** [comment]
nginx' very own allow/deny rules?
http://nginx.org/en/docs/http/ngx_http_access_module.html

**Comment by NicoCaballero** [comment]
thanks... one question more..
how do I associate a location Subcribe to a publisher location.
That is the subcriptos only see messages that location only publisher ?
