### ISSUE TITLE
PPA with Ubuntu package

### ISSUE THREAD

**Issue by mpasternak** [wandenberg/nginx-push-stream-module#184]
Hi,

I created a PPA with Ubuntu 14.04 package here: 
https://launchpad.net/~dotz/+archive/ubuntu/nginx-with-push-stream-module

On Ubuntu, to get all the goodness of your module, just do:
```
sudo apt-add-repository ppa:dotz/nginx-with-push-stream-module
sudo apt-get update
sudo apt-get install nginx
```

I'd love to compile extra packages for other Ubuntu versions, just let me know. 

I realize, that for the real production environments, people will rather tend to compile their own packages. This PPA was created to enable people to be able to get up-and-running with your module fast. Lazy people - programmers. Like me :-)

**Comment by shvchk** [comment]
@mpasternak, nice, thanks a ton!

It would be nice to have this module not only in `nginx-full` package, but also other nginx packages, like `nginx-extras`, `nginx-core`, etc. See http://askubuntu.com/a/556382 for info about difference between these packages.

Also, I think it is better to use latest [release](https://github.com/wandenberg/nginx-push-stream-module/releases), not `master`, as `master` is not considered stable.

**Comment by mpasternak** [comment]
Hey, thanks for positive feedback.

Let's keep this issue open, I'll keep you informed.

**Comment by wandenberg** [comment]
@shvchk I always try to keep the master stable. When new features are under development I keep them at a branch.

@mpasternak what can I do to help?
Can we move this instructions to the wiki and close the issue? Since it isn't in fact an issue.

**Comment by mpasternak** [comment]
Of course.

2015-07-11 23:47 GMT+02:00 Wandenberg Peixoto <notifications@github.com>:

> @shvchk <https://github.com/shvchk> I always try to keep the master
> stable. When new features are under development I keep them at a branch.
>
> @mpasternak <https://github.com/mpasternak> what can I do to help?
> Can we move this instructions to the wiki and close the issue? Since it
> isn't in fact an issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wandenberg/nginx-push-stream-module/issues/184#issuecomment-120663309>
> .
>



-- 
Pozdrawiam,
Michał Pasternak
📱 +48 793 66 87 33

**Comment by wandenberg** [comment]
Done

**Comment by kapv89** [comment]
Hey, the ppa is not working on Ubuntu 15.10
![screenshot from 2016-10-08 02-57-10](https://cloud.githubusercontent.com/assets/1023032/19205924/eea96292-8d02-11e6-8ad4-e8adf98a0674.png)

**Comment by mpasternak** [comment]
It’s not supposed to, I don’t need 15.10. Patches welcome. 

— 
📱+48793668733 📧michal.dtz@gmail.com

**Comment by pp081988** [comment]
大神，牛逼

**Comment by seanlinsley** [comment]
The Ubuntu package didn't end up working for me, though I was able to [compile it from source](https://askubuntu.com/a/280456/411704).

That link is really old, so here's an updated version:
```sh
# Step 1: make sure you don't have multiple PPAs for NGINX installed, e.g. both stable and development.

add-apt-repository -y -s ppa:nginx/stable # -s is important b/c it allows source code access

apt build-dep nginx
cd /tmp
apt source nginx
git clone https://github.com/wandenberg/nginx-push-stream-module.git

cd /tmp/nginx-*/debian/modules
ln -s /tmp/nginx-push-stream-module

vim /tmp/nginx-*/debian/rules
```
Add the module at the end of this:
```make
full_configure_flags := \
                        $(common_configure_flags) \
                        --with-http_addition_module \
                        --with-http_geoip_module=dynamic \
                        --with-http_gunzip_module \
                        --with-http_gzip_static_module \
                        --with-http_image_filter_module=dynamic \
                        --with-http_sub_module \
                        --with-http_xslt_module=dynamic \
                        --with-stream=dynamic \
                        --with-stream_ssl_module \
                        --with-stream_ssl_preread_module \
                        --with-mail=dynamic \
                        --with-mail_ssl_module \
                        --add-dynamic-module=$(MODULESDIR)/http-auth-pam \
                        --add-dynamic-module=$(MODULESDIR)/http-dav-ext \
                        --add-dynamic-module=$(MODULESDIR)/http-echo \
                        --add-dynamic-module=$(MODULESDIR)/http-upstream-fair \
                        --add-dynamic-module=$(MODULESDIR)/http-subs-filter \
                        --add-module=$(MODULESDIR)/nginx-push-stream-module
```

```sh
cd /tmp/nginx-* && dpkg-buildpackage -uc -b -j2

dpkg-deb -I /tmp/nginx-full_*.deb

dpkg -i /tmp/nginx-common_*.deb
dpkg -i /tmp/nginx-full_*.deb


apt-mark hold nginx
apt-mark hold nginx-full
```

**Comment by seanlinsley** [comment]
That works, but I'd really hate to have a regular expression in our source code to edit that makefile...

It turns out NGINX supports dynamic module loading, but I couldn't get it to work. Of the various options ([1](https://www.nginx.com/blog/compiling-dynamic-modules-nginx-plus/), [2](https://www.nginx.com/blog/creating-installable-packages-dynamic-modules/)), I'd always run into an error about the binary being incompatible ¯\\_(ツ)_/¯

**Comment by seanlinsley** [comment]
I don't believe I was aware of it at the time

**Comment by seanlinsley** [comment]
Sorry for not documenting the reason originally. I don't remember what it was anymore :/
