### ISSUE TITLE
push_stream_ping_message_interval   (eventsource)

### ISSUE THREAD

**Issue by NicoCaballero** [wandenberg/nginx-push-stream-module#187]
The above directive does not seem to work with eventsource.
Is this correct ? We   do not get ping message on the  subscriber side when this 
directive is set in eventsource mode.
Thanks.

**Comment by wandenberg** [comment]
While using eventsource connections the ping message is just a comment, something like ":-1".
This way, the connection is kept open due traffic but the client is not notified of a "new message".
You can check this doing a connection with curl command as example.
