### ISSUE TITLE
How to add authentication when sending a message?

### ISSUE THREAD

**Issue by pokal4u** [wandenberg/nginx-push-stream-module#189]
Hi,

Is possible to add authentication when sending a message?

Problem is users without login they can send messages from REST CLIENT.

Ex:  From rest client users post the data to url :  http://www.domain.com?pub=channel.

How could we prevent this?

Thanks
Pokal

**Comment by bastianh** [comment]
You can use nginx functions to restrict access to the url.

http://www.cyberciti.biz/faq/linux-unix-nginx-access-control-howto/
