### ISSUE TITLE
Nginx workers don't quit while a websocket is open

### ISSUE THREAD

**Issue by reist** [wandenberg/nginx-push-stream-module#191]
Hi,

This issue stops Nginx from both quitting (when upgrading, etc) and from refreshing the configuration.
Instead of closing all connections and exiting, one worker stays stuck and locks up Nginx until the connections time out/disconnect.

**Comment by wandenberg** [comment]
Can you provide a minimal but complete example that can reproduce the issue?
I did tests here and is working.
If you are using other module on the same nginx try to isolate them.
