### ISSUE TITLE
push_stream_events_channel_id: End each chunk data with CRLF sequence

### ISSUE THREAD

**Issue by zubinmehta** [wandenberg/nginx-push-stream-module#205]
On subscribing to push_stream_events_channel_id for events, each chunk of JSON ( as the response has Transfer-Encoding: chunked ) should return data ending with CRLF sequence. Currently, I think it isn't doing that.

**Comment by wandenberg** [comment]
Why are you saying that?
The response on that channel has the same format as any other, use the same code.

**Comment by zubinmehta** [comment]
Basically, I was trying to use something like this: http://www.python-requests.org/en/latest/user/advanced/#streaming-requests
at my backend to keep track of who is online, but it wasn't working as it was unable to get lines as there was no CRLF end sequence as required: https://en.wikipedia.org/wiki/Chunked_transfer_encoding#Format

So I am unable to work with it.

PS: I might be wrong here or it could be a requests quirk that I am not aware of !

**Comment by zubinmehta** [comment]
It was a bug with python-requests -> https://github.com/kennethreitz/requests/issues/2433 

Closing this issue.
