### ISSUE TITLE
Broken headers sent for EventSource

### ISSUE THREAD

**Issue by DannyZB** [wandenberg/nginx-push-stream-module#215]
All browsers report the eventsource header to be "text/event-stream; charset=UTF-8"

Internet explorer completely refuses to open the eventstream citing an "illegal content type"

**Comment by wandenberg** [comment]
@DannyZB 

The content-type header is set respecting the [EventSource specification for it](http://www.w3.org/TR/2011/WD-eventsource-20111020/#processing-model).

And as far as I know the Internet Explorer does not natively support this protocol as you can see [here](http://caniuse.com/#search=EventSource)
