### ISSUE TITLE
Connection refused on some android device

### ISSUE THREAD

**Issue by notedit** [wandenberg/nginx-push-stream-module#223]
i am using  longpoll  in my product env.  but some android device  come to the "Connection refused" error

"
2016-01-04 18:18:53:java.net.ConnectException: failed to connect to /101.200.144.186 (port 80): connect failed: ECONNREFUSED (Connection refused)
2016-01-04 18:20:38:java.net.ConnectException: failed to connect to /101.200.144.186 (port 80): connect failed: ECONNREFUSED (Connection refused)
2016-01-04 18:23:03:java.net.ConnectException: failed to connect to /101.200.144.186 (port 80): connect failed: ECONNREFUSED (Connection refused)
"

**Comment by wandenberg** [comment]
This log is from a java application.
Can you check the nginx log? This can be a network problem, not necessarily on push stream module.

**Comment by notedit** [comment]
there are many info like this

"2016/01/04 18:04:02 [info] 10435#0: *393326 client prematurely closed connection, client: 106.74.27.98, server: localhost, request: "GET /sub/10164 HTTP/1.1", host: "101.200.144.186"

**Comment by wandenberg** [comment]
This message proves that the client connected to the server and ended the connection by himself.
The message of ECONNREFUSED is generally related with network configuration, firewall as example.
If on the nginx log you are not seeing erros with "push" on its content or related with exceeded number of connections, there isn't so much I can help.
Have you tried to connect the same client application from a different network?

**Comment by notedit** [comment]
there is no problem in my  testing,  but some of my customers  came to this error.

**Comment by notedit** [comment]
i am using  streaming,  i will test long polling.

**Comment by notedit** [comment]
long polling  has the same  problem

**Comment by wandenberg** [comment]
since there isn't errors on nginx log, and not all your customers have the problem, I keep thinking that is a network problem. Not a problem on the module, and internal tests, like you did, works

**Comment by notedit** [comment]
fixed， it is a MIUI7.0 ROM bug.
