### ISSUE TITLE
Question: Why is pushstream.js not also an npm module?

### ISSUE THREAD

**Issue by gwing33** [wandenberg/nginx-push-stream-module#224]
Is this something I could help start and maintain? Or am I just missing the point with this?

**Comment by wandenberg** [comment]
Hi @gwing33 , what are the advantages of be a npm module?

**Comment by gwing33** [comment]
Thanks for taking the time to respond @wandenberg.

All of our JS is managed on NPM. If we start including a script and not going through our WebPack build, then it will have to get implicitly added in, breaking our ability to easily unit test against it. This starts to break down when I also need this to function for both React Native, NodeJS and the Browser.

I haven't dug through the code too much, but I assume there would need to be some modifications to make it function in those capacities. Also, to have stable JS versions of this would be quite nice outside of my particular use cases.

I ask the question to see if there was a reason I should not do it, or if there is anything in particular to look out for, if I do try and get it into an npm module?

**Comment by wandenberg** [comment]
I don't have the knowledge to say what need to be done, or if there is any problem, to use it as a NPM module.
These client was designed to not require any other framework to work, and I don't have the intention to change this or to convert it to a format that to be used you have to use NPM or bower or any other javascript manager. 
But, if you can achieve a way to use it with NPM without remove the ability to simple "download and use it", I will be glad to verify and merge the changes.
The client has some tests using jasmine, this must continue working :)

**Comment by gwing33** [comment]
Awesome, I'll take a look and see what I can do. Thanks @wandenberg

**Comment by mpasternak** [comment]
I know it's 2019, but here you are: https://www.npmjs.com/package/pushstreamjs 

```
npm install pushstreamjs
```
