### ISSUE TITLE
channels-stats show subscribers not correct

### ISSUE THREAD

**Issue by whtc123** [wandenberg/nginx-push-stream-module#229]
hi ，
    I use nginx-push-stream-module in my product,I need get statistics realtime.normally,it will show subscribers number correct. but ,while nginx tcp layer not recved tcp's FIN or RST package,channels-stats  will not decrease.
 I have tried send_timeout keep_timeout option of nginx,but it's not works.

how can I set timeout for send message to subscriber

**Comment by wandenberg** [comment]
I guess that there isn't nothing that you can do and still respecting the tcp protocol, since a connection is only securely closed after receive those packages or reach a timeout.
Of course you can tweak your OS to have very small timeouts but there are some alerts about this kind of changes.
