### ISSUE TITLE
Nginx crash

### ISSUE THREAD

**Issue by gaopl01202** [wandenberg/nginx-push-stream-module#231]
hello
nginx：1.8.0
push-stream：0.5.1
At first, the program is running normally, but after a few days (5--10days), the nginx will crash.
Nginx process still exists, but is dead.nginx log do not continued to record, but the log nor any abnormalities.
I changed the master version will appear this problem

Now，I don't have any idea. please help me.

**Comment by wandenberg** [comment]
@gaopl01202 please, follow the instructions on this tutorial to create a [core dump](https://www.nginx.com/resources/wiki/start/topics/tutorials/debugging/).
Will be easier to understand what is happening and if the problem is from this module.
Also, use the latest commit available.

**Comment by gaopl01202** [comment]
Thank you. I'll try it.
