### ISSUE TITLE
What's benchmark data for push-stream , who ever did the experiment ?

### ISSUE THREAD

**Issue by ppLorins** [wandenberg/nginx-push-stream-module#238]
What's the benchmark data under specified configuration (like fixed push_stream_shared_memory_size and push_stream_message_ttl), when publisher and subscriber are both in the same local network ?

Who ever did this ?

**Comment by wandenberg** [comment]
There is [this](http://highscalability.com/blog/2014/4/28/how-disqus-went-realtime-with-165k-messages-per-second-and-l.html) quite old post from Disqus with some numbers.
If you are planning to do this metrics using the same machine for the server and client be aware of some OS limitations, like IP/port pairs
