### ISSUE TITLE
Installation nginx-push-stream-module without make

### ISSUE THREAD

**Issue by Akylenok** [wandenberg/nginx-push-stream-module#240]
Hello. I use nginx from engintron for cPanel (CloudLinux OS). Have engintron is not possible to build nginx from source. Is there a possibility that your module plugged in? And if so, how to do it?

**Comment by wandenberg** [comment]
You can generate a .so file with the module, upload it to your server and reference it from your config file.
Check [here](https://www.nginx.com/blog/dynamic-modules-nginx-1-9-11/) for more info.
