### ISSUE TITLE
Must I use "connect" when channel is removed?

### ISSUE THREAD

**Issue by DaaGER** [wandenberg/nginx-push-stream-module#241]
I want know when channel "add" or "remove" I must use "connect" everytime?
Thanks.

**Comment by wandenberg** [comment]
@DaaGER I assumed that you are talking about the methods addChannel e removeChannel from pushstream.js file. If so, checking on the code you can see that if you are already connected and add a new channel, the connection will be closed and opened again. But, on remove is at your control to call the disconnect and connect to reflect immediately. 
My suggestion is make all addChannel calls and them execute the first connection call. If you need to add more channels you only has to call addChannel
