### ISSUE TITLE
Module ignoring severity level of error_log

### ISSUE THREAD

**Issue by iotch** [wandenberg/nginx-push-stream-module#244]
Hello.

v0.5.2 writes to error.log the following info message:

`2016/07/27 18:47:22 [info] 8055#8055: Using 32768KiB of shared memory for push stream module on zone: push_stream_module in /etc/nginx/nginx.conf:49` 

despite of minimum warn level:

`error_log /var/log/nginx/error.log warn;`

Is this expected behaviour?
Thanks.

**Comment by wandenberg** [comment]
@iotch the message is written using the [nginx core functions](https://github.com/wandenberg/nginx-push-stream-module/blob/master/src/ngx_http_push_stream_module_setup.c#L925).
I'm not sure, but messages using the `ngx_conf_log_error` function does not check the error_log level, only messages using `ngx_log_error`.
Anyway, if it is a bug, it is on nginx functions. :smile:

**Comment by iotch** [comment]
Got it, thanks!

**Comment by CrazyLionHeart** [comment]
```
ngx_conf_log_error(NGX_LOG_INFO, cf, 0, "Using %udKiB of shared memory for push stream module on zone: %V", shm_size >> 10, name);
```
NGX_LOG_INFO??

**Comment by wandenberg** [comment]
yes, this message is only an information. A double check on your configuration since the module does a `ngx_align` on the specified value which can change it a little as I understand.
