### ISSUE TITLE
Nginx configuration for Bitrix Environment

### ISSUE THREAD

**Issue by FlorinTronaru** [wandenberg/nginx-push-stream-module#246]
Hi, wandenberg. Could you please assist me? I use a CentOS 7 server, configured with Bitrix Virtual Appliance, and I have problem configuring the nginx to work with Bitrix. So, the adjustment i did was changing the event type from poll to epoll,  and configuration test is succesfully. My problem is that Bitrix still allerts me that is not configured. Any ideea why?

**Comment by wandenberg** [comment]
Hi @FlorinTronaru poll event is not recommended, you are right to change for epoll. (I only use poll for development purposes)
Can you explain a little bit more what do you mean with "Bitrix still allerts me that is not configured"? 
Will be easier try to help you with the exactly problem in hands.
If you are able to reproduce the problem using a Vagrant file will be even better.

**Comment by FlorinTronaru** [comment]
2016-Oct-20 15:41:56 Real time business chat (check_pull_stream): Fail
Connection to 127.0.0.1:8895	Success
Connection to ssl://sv.blike.ro:443	Fail
Socket error [0]: 

Error! Cannot connect to nginx-push-stream module for reading instant messages
2016-Oct-20 15:41:57 Live comments (check_pull_comments): Fail
Error! nginx-push-stream module is required to show comments in real time but not configured properly.
2016-Oct-20 15:41:57 Video calls (check_turn): Fail
Error! nginx-push-stream module is required to make video calls but not configured properly.
2016-Oct-20 15:41:58 Bitrix24 mobile app (check_access_mobile): Warning
Connection to checker.internal.bitrix24.com:80	Success

![github](https://cloud.githubusercontent.com/assets/16703692/19560152/ec6f66e2-96db-11e6-8370-1a126d4a019c.jpg)


Maybe Im wrong, but can happen if I have a socket error on my hands? Because this is my other problem im trying to solve, and this are the only left problems with my server.
I don't have Vagrant on my server, sorry, if you want, I can give you the Bitrix configuration files that are over bitrix-nginx.

**Comment by FlorinTronaru** [comment]
Solved, the socket error was the problem, aperrantly you have to reconfigure SSL and HTTPS to do the trick. Thx for your time and sorry to bother you.
