### ISSUE TITLE
Listen to messages locally

### ISSUE THREAD

**Issue by andrisi** [wandenberg/nginx-push-stream-module#250]
I am sure this can be done by emulating a web client, but I wonder if there is a simpler way to listen to messages on a few channels locally, from a script on the server. To use the push stream modul as a simple message queue. I would not rely on it exclusively, but it would still be a nice way to notify server components.

**Comment by wandenberg** [comment]
It can be used, you only needs a EventSource or WebSocket client, or in the last option use the long polling connection. For the first two I know that are clients on Ruby. In fact I use them on the module tests.

**Comment by andrisi** [comment]
Thanks!
