### ISSUE TITLE
Create as dynamic module option

### ISSUE THREAD

**Issue by jaydlawrence** [wandenberg/nginx-push-stream-module#255]
Since Nginx version 1.9.11, it has supported loading dynamic modules.

This would be really helpful for automating deployments using your library.

For example, importing the geoip module can now be done by:
`sudo apt-get install nginx-module-geoip`

And then in the nginx config, specifying that the module should be loaded manually.
`load_module "modules/ngx_http_geoip_module.so";`

**Comment by wandenberg** [comment]
@jaydlawrence the module is already able to be compiled as a dynamic module. I don't want to take the responsibility to develop a Debian package (or any other distribution package) but feel free to do one, or improve the one mentioned on the [wiki page](https://github.com/wandenberg/nginx-push-stream-module/wiki)

**Comment by jaydlawrence** [comment]
Ok.
Fair enough.
Thanks

**Comment by seanlinsley** [comment]
>the module is already able to be compiled as a dynamic module

... how? 😄
