### ISSUE TITLE
support for nginx server configuration ??

### ISSUE THREAD

**Issue by hiteshsomani** [wandenberg/nginx-push-stream-module#257]
Hi  I have installed `nginx-push-stream-module` version 1.8.0 I have pasted the following code in `/etc/nginx/nginx.conf` 

           location /channels-stats {
       
               push_stream_channels_statistics;

       
                  push_stream_channels_path               $arg_id;
          }

         location /pub {
        
                  push_stream_publisher admin;
  
                  push_stream_channels_path               $arg_id;
         }

          location ~ /sub/(.*) {
       
                   push_stream_subscriber      long-polling;
     
                   push_stream_channels_path         $1;
  
                  push_stream_message_template                "                     {\"id\":~id~,\"channel\":\"~channel~\",\"text\":\"~text~\"}";

        
                  push_stream_longpolling_connection_ttl        30s;
            }

 but getting this error `nginx: [emerg] unknown directive "push_stream_channels_statistics" in     /etc/nginx/nginx.conf:240`

where I'm doing wrong !!

**Comment by wandenberg** [comment]
Do you mind to paste the `nginx -V` output and describe how you installed the module?

**Comment by hiteshsomani** [comment]
ThnQ for quick response nginx -V gives this

           nginx version: nginx/1.10.0 (Ubuntu)
           built with OpenSSL 1.0.2g  1 Mar 2016
           TLS SNI support enabled
           configure arguments: --with-cc-opt='-g -O2 -fPIE -fstack-protector-strong -Wformat - Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_dav_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_v2_module --with-http_sub_module --with-http_xslt_module --with- stream --with-stream_ssl_module --with-mail --with-mail_ssl_module --with-threads

**Comment by hiteshsomani** [comment]
@wandenberg   I have used  `--add-module=../nginx-push-stream-module`  but still getiing the same issue..  I need to confirm where I have to configure the http context ? now I have done at `/etc/nginx/nginx.conf`

**Comment by wandenberg** [comment]
Please, share the full command you are using, and your folder structure, and also your nginx.conf.

**Comment by hiteshsomani** [comment]
command that i'm using : sudo nginx to start server 

getting this error `nginx: [emerg] unknown directive "push_stream_channels_statistics" in /etc/nginx/nginx.conf`

nginx.cong

       server{
     

      location /channels-stats {
       
        push_stream_channels_statistics;

       
        push_stream_channels_path               $arg_id;
    }

    location /pub {
        
        push_stream_publisher admin;

        
        push_stream_channels_path               $arg_id;
    }

    location ~ /sub/(.*) {
       
        push_stream_subscriber      long-polling;

       
        push_stream_channels_path         $1;

        
        push_stream_message_template                "{\"id\":~id~,\"channel\":\"~channel~\",\"text\":\"~text~\"}";

        
        push_stream_longpolling_connection_ttl        30s;
    }



  }

**Comment by wandenberg** [comment]
Not the command to start the server. The command to configure, build and install the nginx.
Probably you made a mistake on it, or forgot to recompile and reinstall after add the --add-module

**Comment by hiteshsomani** [comment]
command I used : I used exactly these steps to install [installation ](https://github.com/wandenberg/nginx-push-stream-module#installation-) 

for configuration I added these code in `/etc/nginx/nginx.conf`: I followed this [configuration](https://github.com/wandenberg/nginx-push-stream-module#basic-configuration) .

**Comment by wandenberg** [comment]
So, for sure you skip some step because on the output of you `nginx -V` does not contain the word 'push' for example and it must be there if you 1) configure the module with --add-module ... 2) recompile the nginx with `make` and 3) reinstalled it with `sudo make install`

**Comment by hiteshsomani** [comment]
Cool Its working but not able to do this ` curl -s -v --no-buffer 'http://localhost/sub/my_channel_1'`

        Trying 127.0.0.1...
        *  connect to 127.0.0.1 port 80 failed: Connection refused
        * Failed to connect to localhost port 80: Connection refused
        * Closing connection 0
any idea !!

**Comment by wandenberg** [comment]
what shows on logs and stdout when you executed `sudo /usr/local/nginx/sbin/nginx -c $NGINX_PUSH_STREAM_MODULE_PATH/misc/nginx.conf`?
(just to remember this `misc/nginx.conf` must not be used for other purposes than testing.)

**Comment by hiteshsomani** [comment]
nothing gets printed :(

**Comment by wandenberg** [comment]
I suggest you to uninstall everything and starts over, step by step. :)

**Comment by hiteshsomani** [comment]
after reinstalling getting this 
   
   nginx: [emerg] invalid event type "poll" in /home/ashwinik/pusher/nginx-push-stream-       module/misc/nginx.conf:19
        nginx: configuration file /home/ashwinik/pusher/nginx-push-stream-module/misc/nginx.conf test failed

**Comment by wandenberg** [comment]
replace poll with epoll if you are on linux and with kqueue if on MacOS

**Comment by hiteshsomani** [comment]
yes I  did it :)

**Comment by hiteshsomani** [comment]
after this command `sudo /usr/local/nginx/sbin/nginx -c $NGINX_PUSH_STREAM_MODULE_PATH/misc/nginx.conf`  when  I hit localhost for channel subcription 

` curl -s -v --no-buffer 'http://localhost/sub/my_channel_1'` nothing is logging

**Comment by hiteshsomani** [comment]
Infact `curl -I http://localhost/`  gives this `curl: (7) Failed to connect to localhost port 80: Connection refused` which means server is not yet started ... but I rab this command `sudo /usr/local/nginx/sbin/nginx -c $NGINX_PUSH_STREAM_MODULE_PATH/misc/nginx.conf`

**Comment by wandenberg** [comment]
the request to /sub location is only logged when it finish. It is a stream connection.
Also, if you are using the misc/nginx.conf without changing the listen line the nginx is listening on `9080` port, not `80`.

**Comment by wandenberg** [comment]
@hiteshsomani I created a Vagrantfile for you.
Just execute a `vagrant up` and after that you will be able to execute `curl --raw localhost:9080/sub/ch1` in one terminal and `curl localhost:9080/pub?id=ch1 -d ABC` in another.

**remamber to rename the file from Vagrantfile.txt to Vagrantfile** 
[Vagrantfile.txt](https://github.com/wandenberg/nginx-push-stream-module/files/910885/Vagrantfile.txt)

**Comment by hiteshsomani** [comment]
@wandenberg ThnQ It's working woopi !!!
