### ISSUE TITLE
Pinging on a broken (client side closed) connection still return NGX_OK

### ISSUE THREAD

**Issue by mr-pajamas** [wandenberg/nginx-push-stream-module#265]
There may be some logical error when invoking nginx http connection api...

**Comment by wandenberg** [comment]
Sorry I could not understand your issue. Can you explain a little bit more? Give examples and describe the problem, please.

**Comment by mr-pajamas** [comment]
OK, Thank you for responding! There is a directive 'push_stream_ping_message_interval' which indicates that push stream module will send ping messages periodically to check whether subscriber connection is still alive. And I've checked the code and find that this module will finalize subscriber connection once ping check fails (rc != NGX_OK). The problem is, ping check seems not to work properly as it always return OK even when subscriber has disconnected. Pending flush, I guess, might cause this problem, as actual write failure cannot be caught and handled.

**Comment by mr-pajamas** [comment]
Here's the relevant code `ngx_http_push_stream_module_utils.c`
```c
static void
ngx_http_push_stream_ping_timer_wake_handler(ngx_event_t *ev)
{
    ngx_http_request_t                 *r = (ngx_http_request_t *) ev->data;
    ngx_http_push_stream_main_conf_t   *mcf = ngx_http_get_module_main_conf(r, ngx_http_push_stream_module);
    ngx_http_push_stream_loc_conf_t    *pslcf = ngx_http_get_module_loc_conf(r, ngx_http_push_stream_module);
    ngx_http_push_stream_module_ctx_t  *ctx = ngx_http_get_module_ctx(r, ngx_http_push_stream_module);
    ngx_int_t                           rc = NGX_OK;

    if ((ctx == NULL) || (ctx->ping_timer == NULL)) {
        return;
    }

    if (pslcf->location_type == NGX_HTTP_PUSH_STREAM_SUBSCRIBER_MODE_EVENTSOURCE) {
        rc = ngx_http_push_stream_send_response_text(r, NGX_HTTP_PUSH_STREAM_EVENTSOURCE_PING_MESSAGE_CHUNK.data, NGX_HTTP_PUSH_STREAM_EVENTSOURCE_PING_MESSAGE_CHUNK.len, 0);
    } else if (pslcf->location_type == NGX_HTTP_PUSH_STREAM_SUBSCRIBER_MODE_WEBSOCKET) {
        rc = ngx_http_push_stream_send_response_text(r, NGX_HTTP_PUSH_STREAM_WEBSOCKET_PING_LAST_FRAME_BYTE, sizeof(NGX_HTTP_PUSH_STREAM_WEBSOCKET_PING_LAST_FRAME_BYTE), 0);
    } else {
        if (mcf->ping_msg == NULL) {
            // create ping message
            if ((mcf->ping_msg == NULL) && (mcf->ping_msg = ngx_http_push_stream_convert_char_to_msg_on_shared(mcf, mcf->ping_message_text.data, mcf->ping_message_text.len, NULL, NGX_HTTP_PUSH_STREAM_PING_MESSAGE_ID, NULL, NULL, 0, 0, r->pool)) == NULL) {
                ngx_log_error(NGX_LOG_ERR, r->connection->log, 0, "push stream module: unable to allocate ping message in shared memory");
            }
        }

        if (mcf->ping_msg != NULL) {
            rc = ngx_http_push_stream_send_response_message(r, NULL, mcf->ping_msg, 1, 0);
        }
    }

    if (rc != NGX_OK) {  // ALWAYS OK HERE!
        ngx_http_push_stream_send_response_finalize(r);  // NEVER REACH HERE
    } else {
        ngx_http_push_stream_timer_reset(pslcf->ping_message_interval, ctx->ping_timer);
    }
}
```

**Comment by wandenberg** [comment]
The point is that Nginx sends the data to the socket and while has space in the socket buffer it will return OK to the module. Once the buffer is full, it means the client is not reading the buffer and has gone, Nginx will return some kind of error to the module making it close the references to that client on the server side and stop trying to send messages to it.
There is no other reliable way to ensure a client has disconnected. I already asked about that on the Nginx email list. This is especially true when using SSL.

**Comment by mr-pajamas** [comment]
So, can I infer that if I make the socket buffer size smaller than ping message body, I can tell if a client connection is alive or not through this way?

**Comment by wandenberg** [comment]
Not exactly. If you set the buffer size smaller than the ping message the module won't be able to send the message, and probably your messages will also be bigger than the ping.
If you really want to detect that the client disconnected faster set a small buffer size, but remember that if you have a slow client the buffer may be full even with the client still online, forcing its disconnection.

**Comment by mr-pajamas** [comment]
I see. Thank you for the advice!
