### ISSUE TITLE
npm/yarn package

### ISSUE THREAD

**Issue by mpasternak** [wandenberg/nginx-push-stream-module#266]
Hi, 

I've repackaged the pushstreamjs file for Yarn/NPM

https://github.com/mpasternak/pushstreamjs

https://www.npmjs.com/package/pushstreamjs

This is just a repackage of that file so it can be installed with yarn. 

Please check if I understood the license properly, your pushstream.js file is MIT licensed but the main repo is GPLv3.

**Comment by wandenberg** [comment]
Yes. you understood correctly.
