### ISSUE TITLE
build as runtime loadable module

### ISSUE THREAD

**Issue by andrisi** [wandenberg/nginx-push-stream-module#269]
Is there a way to build nginx-push-stream-module as a runtime loadable module so that it can be used as many other modules, without recompiling the cure nginx server? Thanks!

**Comment by wandenberg** [comment]
Yes. The same way as other modules. Check #239

**Comment by andrisi** [comment]
Sorry, but brief docs would be great. After building I only find .o files, no .so ones.

**Comment by andrisi** [comment]
I managed to build it - still, some guidance on https://github.com/wandenberg/nginx-push-stream-module would help others. Thanks for all the great work!

**Comment by seanlinsley** [comment]
@andrisi how did you end up building it?

**Comment by andrisi** [comment]
@seanlinsley see https://www.nginx.com/resources/wiki/extending/converting/#compiling-dynamic after downloading the current nginx source, and cloneing the pushstream module into a nearby directory, configuring with "./configure --add-dynamic-module=../nginx-push-stream-module" and then "make modules".

**Comment by seanlinsley** [comment]
Thanks for the update. Unfortunately I already tried that, and ran into an error that said the module wasn't binary compatible with NGINX. The only thing that's worked so far is to compile both NGINX and this module, together: https://github.com/wandenberg/nginx-push-stream-module/issues/184#issuecomment-414158118

**Comment by andrisi** [comment]
You need to build the module with nginx source with the same version as you have on your system.
