### ISSUE TITLE
nginx events method poll to epoll?

### ISSUE THREAD

**Issue by lixuande** [wandenberg/nginx-push-stream-module#271]
I try to use nginx-push-stream-module following the Installation,and test the ../misc/nginx.conf failed, so i cat the nginx.conf find that the nginx events method is poll, I remember nginx used is epoll.The nginx is start ok when i change the poll to epoll.

**Comment by wandenberg** [comment]
Hi @lixuande, the `../misc/nginx.conf` is to be used only during the development/tests and maybe as an example. In normal condition, you should use epoll or kqueue depending on the OS.
I use poll because is easier to simulate some scenarios.
