### ISSUE TITLE
Can't send any string greater than the length of 104 characters

### ISSUE THREAD

**Issue by rahulxxarora** [wandenberg/nginx-push-stream-module#272]
Hey Wandenberg, I have been trying to use the push-stream-module on OSx to send data to the clients connected via websockets. This works fine till the data length of the string is less than 104 characters but doesn't work if the length of the message is greater than that.

I also tried running the following commands on my system:

```
$ sudo sysctl -w kern.ipc.maxsockbuf=16777216
$ sudo sysctl -w net.inet.tcp.sendspace=1048576
$ sudo sysctl -w net.inet.tcp.recvspace=1048576
```

Could you help me out with this?

**Comment by wandenberg** [comment]
Hey @rahulxxarora I will check. Can you provide more information about your environment/test?
Browser version, nginx version, module version, basic configuration to reproduce the issue ...

**Comment by rahulxxarora** [comment]
Hi @wandenberg, the issue has been solved now. It was probably because of the curl command truncating the message. When I tried the same thing with a Python script, it worked.

**Comment by wandenberg** [comment]
OK
