### ISSUE TITLE
Can you do a rpm, deb based package?

### ISSUE THREAD

**Issue by GlebKazantsev** [wandenberg/nginx-push-stream-module#275]
Hello! You do a great job!
But I want to ask - can you build a rpm/deb package for easy install?

**Comment by wandenberg** [comment]
Hi @GlebKazantsev, as discussed in #184 and #247 it is pretty difficult to manage packages that fit all users/OSs and have them working. 
I prefer to not have this on the project, but I encourage others that can provide these packages, to do it and later write at [wiki](https://github.com/wandenberg/nginx-push-stream-module/wiki) page

**Comment by mpasternak** [comment]
@GlebKazantsev for Ubuntu LTS versions please use my small repo https://launchpad.net/~dotz/+archive/ubuntu/nginx-with-push-stream-module
