### ISSUE TITLE
channel stats as a channel?

### ISSUE THREAD

**Issue by andrisi** [wandenberg/nginx-push-stream-module#276]
The channel stats contain important info to monitor clients/services based on server side events, but it needs to be periodically polled to display this info on an admin panel - and this is somehow. In the spirit of the module, it would be nice to have a special predefined channel you could subscribe to that would be filled with administrative events. Channel opened, closed, someone subscribed or dropped - perhaps with chosen granularity. Thanks!

**Comment by wandenberg** [comment]
@andrisi I guess that what you are looking for is provided by the [events_channel](https://github.com/wandenberg/nginx-push-stream-module/blob/master/docs/directives/main.textile#push_stream_events_channel_id-).
The granularity you can do filtering the events on your admin.
To protect this channel from general access you can use this [directive](https://github.com/wandenberg/nginx-push-stream-module/blob/master/docs/directives/subscribers.textile#push_stream_allow_connections_to_events_channel-) if needed.

**Comment by andrisi** [comment]
Great! Again, and again! :-)
