### ISSUE TITLE
Consumer

### ISSUE THREAD

**Issue by snezhkoigor** [wandenberg/nginx-push-stream-module#286]
Hi. For js client I must use only pushstream.js? Or I can use other?

**Comment by wandenberg** [comment]
Hi @snezhkoigor you can use any client that is compatible with the protocol you want to use (WebSocket, EventSoure, long polling).
The pushstream.js is just a wrapper around these making some logic to having a common interface between them and the application code and checking the compatibility with each browser.
But you must be able to use any client that does not require customization for the protocols. For instance, I never tested but I am pretty sure that will not work with socketjs

**Comment by snezhkoigor** [comment]
thanks

I have tried with vue-socket and Laravel-echo and there is no results. I have error by handshake.

**Comment by wandenberg** [comment]
I don't know those two. Which protocol they are trying to use?
