### ISSUE TITLE
Android Client

### ISSUE THREAD

**Issue by subhanshuja** [wandenberg/nginx-push-stream-module#287]
I have a problem when sub or pub into the android client, using OkHttp or another library supporting Http in Android.

If possible, there is an android client library used to nginx-push-stream?

Or any suggestion using Library Http for android client library

thank you

**Comment by wandenberg** [comment]
Hi. What is the problem you are having? Is it using the long polling mode?
You should be able to use any HTTP client setting the correct headers.
