### ISSUE TITLE
All (or almost all) subscribers are registered at one worker

### ISSUE THREAD

**Issue by leverice** [wandenberg/nginx-push-stream-module#288]
My nginx is running in a docker swarm. I realized recently that all (or almost all) of subscribers are at the same worker. Why is it so? How are the subscribers distributed among workers?

Output from push_stream_channels_statistics:
`<infos>
<channels>971</channels>
<wildcard_channels>0</wildcard_channels>
<published_messages>17794</published_messages>
<stored_messages>17794</stored_messages>
<messages_in_trash>0</messages_in_trash>
<channels_in_delete>0</channels_in_delete>
<channels_in_trash>0</channels_in_trash>
<subscribers>15</subscribers>
<uptime>2160</uptime>
<by_worker>
<worker>
<pid>6</pid>
<subscribers>1</subscribers>
<uptime>2160</uptime>
</worker>
<worker>
<pid>7</pid>
<subscribers>14</subscribers>
<uptime>2160</uptime>
</worker>
<worker>
<pid>8</pid>
<subscribers>0</subscribers>
<uptime>2160</uptime>
</worker>
<worker>
<pid>9</pid>
<subscribers>0</subscribers>
<uptime>2160</uptime>
</worker>
</by_worker>
</infos>`

**Comment by wandenberg** [comment]
Hi @leverice  the distribution of requests across Nginx workers is done by the Ngnix, not something that the module can control.
You can look for Nginx configurations like CPU affinity and others connected to this distribution. ;)

**Comment by leverice** [comment]
@wandenberg Thanks! I also suspected this but wanted to be sure. So, basically, the worker that got the initial websocket request will be responsible for the subscriber, right?

**Comment by leverice** [comment]
For those who has the same issue: look at **reuseport** directive.

**Comment by wandenberg** [comment]
Yes. The worker with the connection (doesn't matter if WebSocket or long polling or ... ) will be responsible for the subscriber.
