### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by snezhkoigor** [wandenberg/nginx-push-stream-module#289]
```
2019/12/12 15:44:47 [error] 20080#20080: *68645 push stream module: Don't have at least one of the mandatory headers: Connection, Upgrade, Sec-WebSocket-Key and Sec-WebSocket-Version, client: ..., server: ..., request: "GET //ws/981241337ccd5a64c07b2077d42d870f?_=1576154687211&tag=&time=Thu%2C%2012%20Dec%202019%2012%3A44%3A07%20GMT&eventid= HTTP/1.1", host: "..."
```

What to do with this?

**Comment by wandenberg** [comment]
@snezhkoigor what kind of WS client are you using?
The message indicates that the client that is being used is not compatible with the WebSocket protocol implemented on the module, or that something on the request path is striping at least one of the required headers.
Can you give more information about your environment, configuration and use case?

**Comment by snezhkoigor** [comment]
> @snezhkoigor what kind of WS client are you using?
> The message indicates that the client that is being used is not compatible with the WebSocket protocol implemented on the module, or that something on the request path is striping at least one of the required headers.
> Can you give more information about your environment, configuration and use case?

pushstream.js

Some time before all worked perfect. But now I see this in logs.

**Comment by wandenberg** [comment]
Can you change the error log format to log the user agent of the request?
It might be some client just scanning the WebSocket port or some incompatible browser.
With the user agent, we might be able to find out.

**Comment by snezhkoigor** [comment]
> Can you change the error log format to log the user agent of the request?
> It might be some client just scanning the WebSocket port or some incompatible browser.
> With the user agent, we might be able to find out.

ok. will send later.

**Comment by wandenberg** [comment]
have you found something @snezhkoigor ?
