### ISSUE TITLE
can we get a new release for m1 apple silicon fix?

### ISSUE THREAD

**Issue by kpmueller** [wandenberg/nginx-push-stream-module#296]
There was a bug fix merged (thank you!) in PR #293 to make things work on the new m1 apple silicon CPUs, but we never had a 0.5.5 (or whatever) release done. 

I don't know if there is a reason for this, or if other work is expected that is being waited on, but I thought I would ask.

thanks much!

**Comment by sunnychun** [comment]
您的信已收到，我将尽快给您答复

**Comment by wandenberg** [comment]
Done
