### ISSUE TITLE
Unload event is deprecated

### ISSUE THREAD

**Issue by d-javu** [wandenberg/nginx-push-stream-module#309]
The unload event is deprecated and Lighthouse complains and docks a few points.

See the following for information on deprecation:
https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event
https://developer.chrome.com/docs/web-platform/deprecating-unload

The unload event is used to call disconnect(), which the browser will do for us anyway when navigating away from the page.

Is there some necessary magic going on here, or should handling of the unload event just be dropped?

See pull request:  #310

**Comment by sunnychun** [comment]
您的信已收到，我将尽快给您答复

**Comment by wandenberg** [comment]
Thanks for calling my attention to this @d-javu
