### ISSUE TITLE
how can i push msg to specific user via websocket/stream

### ISSUE THREAD

**Issue by windbug** [wandenberg/nginx-push-stream-module#70]
Hi.

most of all, i send push msg every user.
but sometimes, must send push msg to Only 1 User.

so, i wanna open multi websocket/stream.
how can i  push msg to specific user via websocket/stream?
or how can i use authorized socket?
ex)
 e-mail Alert
Messenger Alert
Private chat

**Comment by Jeremlicious** [comment]
Good tip!
What if we `pushstream.addChannel('anIdFromAjaxRequest')` multiple time after an Ajax request ?
I thought we could disconnect, do all the addChannel and reconnect again so the websocket will connect only once. But we might never get messages that would have been received between the disconect and connect.

**Comment by wandenberg** [comment]
@Jeremlicious You can control the time you want to connect if you disconnect first. If you are already connected, each call to addChannel will make the client disconnect and connect again.
About loose messages during this period, it depends on how you configured your server, to store or not old messages, and on your client code, if it is setting that it wants to receive old messages based on one of the ways to get old messages. Take a look on the examples.

**Comment by Jeremlicious** [comment]
Thanks for your quick reply.
I found a hack to avoid disconnecting first :
```js
// Get new channels names via Ajax
pushstream.readyState=0
// pushstream.addChannel(eachNewOne)
pushstream.connect()
```

Maybe `addChannel` could be changed and accept an array of channels names ? I can code it if you are ok.
Cheers.

**Comment by wandenberg** [comment]
@Jeremlicious definitely change the `readyState` on this way is not a good idea.
You can add a `addChannels` method, just do not forgot to add tests to it. ;)
