### ISSUE TITLE
Add a way to queue messages only until delivered to a subscriber

### ISSUE THREAD

**Issue by Kronuz** [wandenberg/nginx-push-stream-module#93]
Nginx Push Module has this option that I used. It would be nice to have an equivalent:

```
push_delete_oldest_received_message [ off ]
default: 0
context: http, server, location
When enabled, as soon as the oldest message
in a channel's message queue has been received
by a subscriber, it is deleted -- provided
there are more than push_max_message_buffer_length
messages in the channel's message buffer.
```

Although it then goes to recommend against it use:
"Recommend avoiding this directive as it violates subscribers' assumptions of GET request idempotence."

**Comment by wandenberg** [comment]
If the goal is to reduce the number of returned messages it can be achieved using the `if-modified-since` and `if-none-match` headers.
